<a href="https://colab.research.google.com/github/megharajs07/DAV1/blob/main/Pandas_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pandas

## Pandas - 1

- Introduction to Pandas
- Dataframe (`df`) and series
- Basic operations on Columns
- Basic operations on Rows
- `loc` and `iloc` for indexes
- Columns as Row Index

---

#### Introduction to Pandas:

- in numpy the data is homogeneous
- pandas are 2D matrices where each column can have different datatype like a database table

In [ ]:
import pandas as pd

In [ ]:
!wget "https://drive.google.com/uc?export=download&id=1E3bwvYGf1ig32RmcYiWc0IXPN-mD_bI_" -O mckinsey.csv

--2024-10-23 12:20:40--  https://drive.google.com/uc?export=download&id=1E3bwvYGf1ig32RmcYiWc0IXPN-mD_bI_
Resolving drive.google.com (drive.google.com)... 142.251.179.100, 142.251.179.139, 142.251.179.138, ...
Connecting to drive.google.com (drive.google.com)|142.251.179.100|:443... connected.
HTTP request sent, awaiting response... 303 See Other
Location: https://drive.usercontent.google.com/download?id=1E3bwvYGf1ig32RmcYiWc0IXPN-mD_bI_&export=download [following]
--2024-10-23 12:20:40--  https://drive.usercontent.google.com/download?id=1E3bwvYGf1ig32RmcYiWc0IXPN-mD_bI_&export=download
Resolving drive.usercontent.google.com (drive.usercontent.google.com)... 172.253.63.132, 2607:f8b0:4004:c08::84
Connecting to drive.usercontent.google.com (drive.usercontent.google.com)|172.253.63.132|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 83785 (82K) [application/octet-stream]
Saving to: ‘mckinsey.csv’

mckinsey.csv        100%[===================>]  81.82K  --.-KB/s    in 0.008s

2024-10-23 12:20:43 (9.87 MB/s) - ‘mckinsey.csv’ saved [83785/83785]

In [ ]:
df = pd.read_csv("mckinsey.csv")
df.head()

       country  year  population continent  life_exp     gdp_cap
0  Afghanistan  1952     8425333      Asia    28.801  779.445314
1  Afghanistan  1957     9240934      Asia    30.332  820.853030
2  Afghanistan  1962    10267083      Asia    31.997  853.100710
3  Afghanistan  1967    11537966      Asia    34.020  836.197138
4  Afghanistan  1972    13079460      Asia    36.088  739.981106

In [ ]:
df.head(20)

        country  year  population continent  life_exp      gdp_cap
0   Afghanistan  1952     8425333      Asia    28.801   779.445314
1   Afghanistan  1957     9240934      Asia    30.332   820.853030
2   Afghanistan  1962    10267083      Asia    31.997   853.100710
3   Afghanistan  1967    11537966      Asia    34.020   836.197138
4   Afghanistan  1972    13079460      Asia    36.088   739.981106
5   Afghanistan  1977    14880372      Asia    38.438   786.113360
6   Afghanistan  1982    12881816      Asia    39.854   978.011439
7   Afghanistan  1987    13867957      Asia    40.822   852.395945
8   Afghanistan  1992    16317921      Asia    41.674   649.341395
9   Afghanistan  1997    22227415      Asia    41.763   635.341351
10  Afghanistan  2002    25268405      Asia    42.129   726.734055
11  Afghanistan  2007    31889923      Asia    43.828   974.580338
12      Albania  1952     1282697    Europe    55.230  1601.056136
13      Albania  1957     1476505    Europe    59.280  1942.284244
14      Albania  1962     1728137    Europe    64.820  2312.888958
15      Albania  1967     1984060    Europe    66.220  2760.196931
16      Albania  1972     2263554    Europe    67.690  3313.422188
17      Albania  1977     2509048    Europe    68.930  3533.003910
18      Albania  1982     2780097    Europe    70.420  3630.880722
19      Albania  1987     3075321    Europe    72.000  3738.932735

In [ ]:
df.shape

(1704, 6)

In [ ]:
type(df)

pandas.core.frame.DataFrame

In [ ]:
df['country']

0       Afghanistan
1       Afghanistan
2       Afghanistan
3       Afghanistan
4       Afghanistan
           ...
1699       Zimbabwe
1700       Zimbabwe
1701       Zimbabwe
1702       Zimbabwe
1703       Zimbabwe
Name: country, Length: 1704, dtype: object

In [ ]:
type(df['year'])

pandas.core.series.Series

In [ ]:
df['year'][5]

1977

In [ ]:
df['year'][:5]

0    1952
1    1957
2    1962
3    1967
4    1972
Name: year, dtype: int64

In [ ]:
cols = ['country', 'year']
df[cols]

          country  year
0     Afghanistan  1952
1     Afghanistan  1957
2     Afghanistan  1962
3     Afghanistan  1967
4     Afghanistan  1972
...           ...   ...
1699     Zimbabwe  1987
1700     Zimbabwe  1992
1701     Zimbabwe  1997
1702     Zimbabwe  2002
1703     Zimbabwe  2007

[1704 rows x 2 columns]

In [ ]:
type(df[cols])

pandas.core.frame.DataFrame

In [ ]:
df['population']

0        8425333
1        9240934
2       10267083
3       11537966
4       13079460
          ...
1699     9216418
1700    10704340
1701    11404948
1702    11926563
1703    12311143
Name: population, Length: 1704, dtype: int64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1704 entries, 0 to 1703
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   country     1704 non-null   object
 1   year        1704 non-null   int64
 2   population  1704 non-null   int64
 3   continent   1704 non-null   object
 4   life_exp    1704 non-null   float64
 5   gdp_cap     1704 non-null   float64
dtypes: float64(2), int64(2), object(2)
memory usage: 80.0+ KB

In [ ]:
df.columns

Index(['country', 'year', 'population', 'continent', 'life_exp', 'gdp_cap'], dtype='object')

In [ ]:
dict_users = {
                "userid":[1, 2, 3],
                "name":["sharadh", "shahid", "khushal"]
              }
type(dict_users)

dict

In [ ]:
pd.DataFrame(dict_users)

   userid     name
0       1  sharadh
1       2   shahid
2       3  khushal

### Basic Operations

- Columns
  - Add new columns
  - Delete Columns
  - Rename Columns

In [ ]:
df.columns

Index(['country', 'year', 'population', 'continent', 'life_exp', 'gdp_cap'], dtype='object')

In [ ]:
df.keys()

Index(['country', 'year', 'population', 'continent', 'life_exp', 'gdp_cap'], dtype='object')

In [ ]:
df["country"]

0       Afghanistan
1       Afghanistan
2       Afghanistan
3       Afghanistan
4       Afghanistan
           ...
1699       Zimbabwe
1700       Zimbabwe
1701       Zimbabwe
1702       Zimbabwe
1703       Zimbabwe
Name: country, Length: 1704, dtype: object

Unique values in series

In [ ]:
df["country"].unique()

array(['Afghanistan', 'Albania', 'Algeria', 'Angola', 'Argentina',
       'Australia', 'Austria', 'Bahrain', 'Bangladesh', 'Belgium',
       'Benin', 'Bolivia', 'Bosnia and Herzegovina', 'Botswana', 'Brazil',
       'Bulgaria', 'Burkina Faso', 'Burundi', 'Cambodia', 'Cameroon',
       'Canada', 'Central African Republic', 'Chad', 'Chile', 'China',
       'Colombia', 'Comoros', 'Congo, Dem. Rep.', 'Congo, Rep.',
       'Costa Rica', "Cote d'Ivoire", 'Croatia', 'Cuba', 'Czech Republic',
       'Denmark', 'Djibouti', 'Dominican Republic', 'Ecuador', 'Egypt',
       'El Salvador', 'Equatorial Guinea', 'Eritrea', 'Ethiopia',
       'Finland', 'France', 'Gabon', 'Gambia', 'Germany', 'Ghana',
       'Greece', 'Guatemala', 'Guinea', 'Guinea-Bissau', 'Haiti',
       'Honduras', 'Hong Kong, China', 'Hungary', 'Iceland', 'India',
       'Indonesia', 'Iran', 'Iraq', 'Ireland', 'Israel', 'Italy',
       'Jamaica', 'Japan', 'Jordan', 'Kenya', 'Korea, Dem. Rep.',
       'Korea, Rep.', 'Kuwait', 'Lebanon', 'Lesotho', 'Liberia', 'Libya',
       'Madagascar', 'Malawi', 'Malaysia', 'Mali', 'Mauritania',
       'Mauritius', 'Mexico', 'Mongolia', 'Montenegro', 'Morocco',
       'Mozambique', 'Myanmar', 'Namibia', 'Nepal', 'Netherlands',
       'New Zealand', 'Nicaragua', 'Niger', 'Nigeria', 'Norway', 'Oman',
       'Pakistan', 'Panama', 'Paraguay', 'Peru', 'Philippines', 'Poland',
       'Portugal', 'Puerto Rico', 'Reunion', 'Romania', 'Rwanda',
       'Sao Tome and Principe', 'Saudi Arabia', 'Senegal', 'Serbia',
       'Sierra Leone', 'Singapore', 'Slovak Republic', 'Slovenia',
       'Somalia', 'South Africa', 'Spain', 'Sri Lanka', 'Sudan',
       'Swaziland', 'Sweden', 'Switzerland', 'Syria', 'Taiwan',
       'Tanzania', 'Thailand', 'Togo', 'Trinidad and Tobago', 'Tunisia',
       'Turkey', 'Uganda', 'United Kingdom', 'United States', 'Uruguay',
       'Venezuela', 'Vietnam', 'West Bank and Gaza', 'Yemen, Rep.',
       'Zambia', 'Zimbabwe'], dtype=object)

In [ ]:
len(df["country"].unique())

142

In [ ]:
df["country"].nunique()

142

In [ ]:
df["country"].value_counts()

country
Afghanistan          12
Pakistan             12
New Zealand          12
Nicaragua            12
Niger                12
                     ..
Eritrea              12
Equatorial Guinea    12
El Salvador          12
Egypt                12
Zimbabwe             12
Name: count, Length: 142, dtype: int64

In [ ]:
df["year"].value_counts()

year
1952    142
1957    142
1962    142
1967    142
1972    142
1977    142
1982    142
1987    142
1992    142
1997    142
2002    142
2007    142
Name: count, dtype: int64

In [ ]:
df["continent"].value_counts()

continent
Africa      624
Asia        396
Europe      360
Americas    300
Oceania      24
Name: count, dtype: int64

In [ ]:
df["continent"].value_counts()[::-1]

continent
Oceania      24
Americas    300
Europe      360
Asia        396
Africa      624
Name: count, dtype: int64

### Rename columns

We can rename columns by
1.   passing the dictionary with old_name: new_name pair
2.   specifying axis = 1

In [ ]:
df.columns

Index(['country', 'year', 'population', 'continent', 'life_exp', 'gdp_cap'], dtype='object')

In [ ]:
dict1 = {"population": "countofpeople", "life_exp": "life_expectancy"}

In [ ]:
df.rename(columns = dict1) # rename column index

          country  year  countofpeople continent  life_expectancy     gdp_cap
0     Afghanistan  1952        8425333      Asia           28.801  779.445314
1     Afghanistan  1957        9240934      Asia           30.332  820.853030
2     Afghanistan  1962       10267083      Asia           31.997  853.100710
3     Afghanistan  1967       11537966      Asia           34.020  836.197138
4     Afghanistan  1972       13079460      Asia           36.088  739.981106
...           ...   ...            ...       ...              ...         ...
1699     Zimbabwe  1987        9216418    Africa           62.351  706.157306
1700     Zimbabwe  1992       10704340    Africa           60.377  693.420786
1701     Zimbabwe  1997       11404948    Africa           46.809  792.449960
1702     Zimbabwe  2002       11926563    Africa           39.989  672.038623
1703     Zimbabwe  2007       12311143    Africa           43.487  469.709298

[1704 rows x 6 columns]

In [ ]:
df.rename(dict1, axis = 1) # rename column index

          country  year  countofpeople continent  life_expectancy     gdp_cap
0     Afghanistan  1952        8425333      Asia           28.801  779.445314
1     Afghanistan  1957        9240934      Asia           30.332  820.853030
2     Afghanistan  1962       10267083      Asia           31.997  853.100710
3     Afghanistan  1967       11537966      Asia           34.020  836.197138
4     Afghanistan  1972       13079460      Asia           36.088  739.981106
...           ...   ...            ...       ...              ...         ...
1699     Zimbabwe  1987        9216418    Africa           62.351  706.157306
1700     Zimbabwe  1992       10704340    Africa           60.377  693.420786
1701     Zimbabwe  1997       11404948    Africa           46.809  792.449960
1702     Zimbabwe  2002       11926563    Africa           39.989  672.038623
1703     Zimbabwe  2007       12311143    Africa           43.487  469.709298

[1704 rows x 6 columns]

### Create a new column
1) Use existinng column to create new col

2) Create new col from new data

In [ ]:
df['year'] + 10

0       1962
1       1967
2       1972
3       1977
4       1982
        ...
1699    1997
1700    2002
1701    2007
1702    2012
1703    2017
Name: year, Length: 1704, dtype: int64

In [ ]:
df['year+10'] = df['year'] + 10

In [ ]:
df.head()

       country  year  population continent  life_exp     gdp_cap  year+10
0  Afghanistan  1952     8425333      Asia    28.801  779.445314     1962
1  Afghanistan  1957     9240934      Asia    30.332  820.853030     1967
2  Afghanistan  1962    10267083      Asia    31.997  853.100710     1972
3  Afghanistan  1967    11537966      Asia    34.020  836.197138     1977
4  Afghanistan  1972    13079460      Asia    36.088  739.981106     1982

### deleting a column

In [ ]:
df.drop('year+10', axis = 1)

          country  year  population continent  life_exp     gdp_cap
0     Afghanistan  1952     8425333      Asia    28.801  779.445314
1     Afghanistan  1957     9240934      Asia    30.332  820.853030
2     Afghanistan  1962    10267083      Asia    31.997  853.100710
3     Afghanistan  1967    11537966      Asia    34.020  836.197138
4     Afghanistan  1972    13079460      Asia    36.088  739.981106
...           ...   ...         ...       ...       ...         ...
1699     Zimbabwe  1987     9216418    Africa    62.351  706.157306
1700     Zimbabwe  1992    10704340    Africa    60.377  693.420786
1701     Zimbabwe  1997    11404948    Africa    46.809  792.449960
1702     Zimbabwe  2002    11926563    Africa    39.989  672.038623
1703     Zimbabwe  2007    12311143    Africa    43.487  469.709298

[1704 rows x 6 columns]

In [ ]:
df

          country  year  population continent  life_exp     gdp_cap  year+10
0     Afghanistan  1952     8425333      Asia    28.801  779.445314     1962
1     Afghanistan  1957     9240934      Asia    30.332  820.853030     1967
2     Afghanistan  1962    10267083      Asia    31.997  853.100710     1972
3     Afghanistan  1967    11537966      Asia    34.020  836.197138     1977
4     Afghanistan  1972    13079460      Asia    36.088  739.981106     1982
...           ...   ...         ...       ...       ...         ...      ...
1699     Zimbabwe  1987     9216418    Africa    62.351  706.157306     1997
1700     Zimbabwe  1992    10704340    Africa    60.377  693.420786     2002
1701     Zimbabwe  1997    11404948    Africa    46.809  792.449960     2007
1702     Zimbabwe  2002    11926563    Africa    39.989  672.038623     2012
1703     Zimbabwe  2007    12311143    Africa    43.487  469.709298     2017

[1704 rows x 7 columns]

In [ ]:
df = df.drop('year+10', axis = 1)

In [ ]:
df

          country  year  population continent  life_exp     gdp_cap
0     Afghanistan  1952     8425333      Asia    28.801  779.445314
1     Afghanistan  1957     9240934      Asia    30.332  820.853030
2     Afghanistan  1962    10267083      Asia    31.997  853.100710
3     Afghanistan  1967    11537966      Asia    34.020  836.197138
4     Afghanistan  1972    13079460      Asia    36.088  739.981106
...           ...   ...         ...       ...       ...         ...
1699     Zimbabwe  1987     9216418    Africa    62.351  706.157306
1700     Zimbabwe  1992    10704340    Africa    60.377  693.420786
1701     Zimbabwe  1997    11404948    Africa    46.809  792.449960
1702     Zimbabwe  2002    11926563    Africa    39.989  672.038623
1703     Zimbabwe  2007    12311143    Africa    43.487  469.709298

[1704 rows x 6 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1704 entries, 0 to 1703
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   country     1704 non-null   object
 1   year        1704 non-null   int64
 2   population  1704 non-null   int64
 3   continent   1704 non-null   object
 4   life_exp    1704 non-null   float64
 5   gdp_cap     1704 non-null   float64
dtypes: float64(2), int64(2), object(2)
memory usage: 80.0+ KB

In [ ]:
df.head()

       country  year  population continent  life_exp     gdp_cap
0  Afghanistan  1952     8425333      Asia    28.801  779.445314
1  Afghanistan  1957     9240934      Asia    30.332  820.853030
2  Afghanistan  1962    10267083      Asia    31.997  853.100710
3  Afghanistan  1967    11537966      Asia    34.020  836.197138
4  Afghanistan  1972    13079460      Asia    36.088  739.981106

In [ ]:
df.shape

(1704, 6)

In [ ]:
df.ndim

2

In [ ]:
df.keys()

Index(['country', 'year', 'population', 'continent', 'life_exp', 'gdp_cap'], dtype='object')

In [ ]:
df["country"].unique()

array(['Afghanistan', 'Albania', 'Algeria', 'Angola', 'Argentina',
       'Australia', 'Austria', 'Bahrain', 'Bangladesh', 'Belgium',
       'Benin', 'Bolivia', 'Bosnia and Herzegovina', 'Botswana', 'Brazil',
       'Bulgaria', 'Burkina Faso', 'Burundi', 'Cambodia', 'Cameroon',
       'Canada', 'Central African Republic', 'Chad', 'Chile', 'China',
       'Colombia', 'Comoros', 'Congo, Dem. Rep.', 'Congo, Rep.',
       'Costa Rica', "Cote d'Ivoire", 'Croatia', 'Cuba', 'Czech Republic',
       'Denmark', 'Djibouti', 'Dominican Republic', 'Ecuador', 'Egypt',
       'El Salvador', 'Equatorial Guinea', 'Eritrea', 'Ethiopia',
       'Finland', 'France', 'Gabon', 'Gambia', 'Germany', 'Ghana',
       'Greece', 'Guatemala', 'Guinea', 'Guinea-Bissau', 'Haiti',
       'Honduras', 'Hong Kong, China', 'Hungary', 'Iceland', 'India',
       'Indonesia', 'Iran', 'Iraq', 'Ireland', 'Israel', 'Italy',
       'Jamaica', 'Japan', 'Jordan', 'Kenya', 'Korea, Dem. Rep.',
       'Korea, Rep.', 'Kuwait', 'Lebanon', 'Lesotho', 'Liberia', 'Libya',
       'Madagascar', 'Malawi', 'Malaysia', 'Mali', 'Mauritania',
       'Mauritius', 'Mexico', 'Mongolia', 'Montenegro', 'Morocco',
       'Mozambique', 'Myanmar', 'Namibia', 'Nepal', 'Netherlands',
       'New Zealand', 'Nicaragua', 'Niger', 'Nigeria', 'Norway', 'Oman',
       'Pakistan', 'Panama', 'Paraguay', 'Peru', 'Philippines', 'Poland',
       'Portugal', 'Puerto Rico', 'Reunion', 'Romania', 'Rwanda',
       'Sao Tome and Principe', 'Saudi Arabia', 'Senegal', 'Serbia',
       'Sierra Leone', 'Singapore', 'Slovak Republic', 'Slovenia',
       'Somalia', 'South Africa', 'Spain', 'Sri Lanka', 'Sudan',
       'Swaziland', 'Sweden', 'Switzerland', 'Syria', 'Taiwan',
       'Tanzania', 'Thailand', 'Togo', 'Trinidad and Tobago', 'Tunisia',
       'Turkey', 'Uganda', 'United Kingdom', 'United States', 'Uruguay',
       'Venezuela', 'Vietnam', 'West Bank and Gaza', 'Yemen, Rep.',
       'Zambia', 'Zimbabwe'], dtype=object)

In [ ]:
df["country"].value_counts()

country
Afghanistan          12
Pakistan             12
New Zealand          12
Nicaragua            12
Niger                12
                     ..
Eritrea              12
Equatorial Guinea    12
El Salvador          12
Egypt                12
Zimbabwe             12
Name: count, Length: 142, dtype: int64

In [ ]:
142*12

1704

In [ ]:
df.head()

       country  year  population continent  life_exp     gdp_cap
0  Afghanistan  1952     8425333      Asia    28.801  779.445314
1  Afghanistan  1957     9240934      Asia    30.332  820.853030
2  Afghanistan  1962    10267083      Asia    31.997  853.100710
3  Afghanistan  1967    11537966      Asia    34.020  836.197138
4  Afghanistan  1972    13079460      Asia    36.088  739.981106

In [ ]:
df.rename({"population": "Population", "country": "Country"}, axis =1)

          Country  year  Population continent  life_exp     gdp_cap
0     Afghanistan  1952     8425333      Asia    28.801  779.445314
1     Afghanistan  1957     9240934      Asia    30.332  820.853030
2     Afghanistan  1962    10267083      Asia    31.997  853.100710
3     Afghanistan  1967    11537966      Asia    34.020  836.197138
4     Afghanistan  1972    13079460      Asia    36.088  739.981106
...           ...   ...         ...       ...       ...         ...
1699     Zimbabwe  1987     9216418    Africa    62.351  706.157306
1700     Zimbabwe  1992    10704340    Africa    60.377  693.420786
1701     Zimbabwe  1997    11404948    Africa    46.809  792.449960
1702     Zimbabwe  2002    11926563    Africa    39.989  672.038623
1703     Zimbabwe  2007    12311143    Africa    43.487  469.709298

[1704 rows x 6 columns]

In [ ]:
df

          country  year  population continent  life_exp     gdp_cap
0     Afghanistan  1952     8425333      Asia    28.801  779.445314
1     Afghanistan  1957     9240934      Asia    30.332  820.853030
2     Afghanistan  1962    10267083      Asia    31.997  853.100710
3     Afghanistan  1967    11537966      Asia    34.020  836.197138
4     Afghanistan  1972    13079460      Asia    36.088  739.981106
...           ...   ...         ...       ...       ...         ...
1699     Zimbabwe  1987     9216418    Africa    62.351  706.157306
1700     Zimbabwe  1992    10704340    Africa    60.377  693.420786
1701     Zimbabwe  1997    11404948    Africa    46.809  792.449960
1702     Zimbabwe  2002    11926563    Africa    39.989  672.038623
1703     Zimbabwe  2007    12311143    Africa    43.487  469.709298

[1704 rows x 6 columns]

In [ ]:
df['gdp'] = df['gdp_cap'] * df['population']

In [ ]:
df

,country,year,population,continent,life_exp,gdp_cap,gdp
0,Afghanistan,1952,8425333,Asia,28.801,779.445314,6.567086e+09
1,Afghanistan,1957,9240934,Asia,30.332,820.853030,7.585449e+09
2,Afghanistan,1962,10267083,Asia,31.997,853.100710,8.758856e+09
3,Afghanistan,1967,11537966,Asia,34.020,836.197138,9.648014e+09
4,Afghanistan,1972,13079460,Asia,36.088,739.981106,9.678553e+09
...,...,...,...,...,...,...,...
1699,Zimbabwe,1987,9216418,Africa,62.351,706.157306,6.508241e+09
1700,Zimbabwe,1992,10704340,Africa,60.377,693.420786,7.422612e+09
1701,Zimbabwe,1997,11404948,Africa,46.809,792.449960,9.037851e+09
1702,Zimbabwe,2002,11926563,Africa,39.989,672.038623,8.015111e+09
1703,Zimbabwe,2007,12311143,Africa,43.487,469.709298,5.782658e+09

In [ ]:
df.head()

       country  year  population continent  life_exp     gdp_cap           gdp
0  Afghanistan  1952     8425333      Asia    28.801  779.445314  6.567086e+09
1  Afghanistan  1957     9240934      Asia    30.332  820.853030  7.585449e+09
2  Afghanistan  1962    10267083      Asia    31.997  853.100710  8.758856e+09
3  Afghanistan  1967    11537966      Asia    34.020  836.197138  9.648014e+09
4  Afghanistan  1972    13079460      Asia    36.088  739.981106  9.678553e+09

In [ ]:
df.shape

(1704, 7)

In [ ]:
df.index = [i for i in range(10, 1714)]
df

,country,year,population,continent,life_exp,gdp_cap,gdp
10,Afghanistan,1952,8425333,Asia,28.801,779.445314,6.567086e+09
11,Afghanistan,1957,9240934,Asia,30.332,820.853030,7.585449e+09
12,Afghanistan,1962,10267083,Asia,31.997,853.100710,8.758856e+09
13,Afghanistan,1967,11537966,Asia,34.020,836.197138,9.648014e+09
14,Afghanistan,1972,13079460,Asia,36.088,739.981106,9.678553e+09
...,...,...,...,...,...,...,...
1709,Zimbabwe,1987,9216418,Africa,62.351,706.157306,6.508241e+09
1710,Zimbabwe,1992,10704340,Africa,60.377,693.420786,7.422612e+09
1711,Zimbabwe,1997,11404948,Africa,46.809,792.449960,9.037851e+09
1712,Zimbabwe,2002,11926563,Africa,39.989,672.038623,8.015111e+09
1713,Zimbabwe,2007,12311143,Africa,43.487,469.709298,5.782658e+09

In [ ]:
a = pd.Series(['a','b','c'], index=[1,2,2])
print(a[2])

2    b
2    c
dtype: object

In [ ]:
df

,country,year,population,continent,life_exp,gdp_cap,gdp
10,Afghanistan,1952,8425333,Asia,28.801,779.445314,6.567086e+09
11,Afghanistan,1957,9240934,Asia,30.332,820.853030,7.585449e+09
12,Afghanistan,1962,10267083,Asia,31.997,853.100710,8.758856e+09
13,Afghanistan,1967,11537966,Asia,34.020,836.197138,9.648014e+09
14,Afghanistan,1972,13079460,Asia,36.088,739.981106,9.678553e+09
...,...,...,...,...,...,...,...
1709,Zimbabwe,1987,9216418,Africa,62.351,706.157306,6.508241e+09
1710,Zimbabwe,1992,10704340,Africa,60.377,693.420786,7.422612e+09
1711,Zimbabwe,1997,11404948,Africa,46.809,792.449960,9.037851e+09
1712,Zimbabwe,2002,11926563,Africa,39.989,672.038623,8.015111e+09
1713,Zimbabwe,2007,12311143,Africa,43.487,469.709298,5.782658e+09

In [ ]:
pd.DataFrame(df, columns = ["life_exp", "country", "year"])

      life_exp      country  year
10      28.801  Afghanistan  1952
11      30.332  Afghanistan  1957
12      31.997  Afghanistan  1962
13      34.020  Afghanistan  1967
14      36.088  Afghanistan  1972
...        ...          ...   ...
1709    62.351     Zimbabwe  1987
1710    60.377     Zimbabwe  1992
1711    46.809     Zimbabwe  1997
1712    39.989     Zimbabwe  2002
1713    43.487     Zimbabwe  2007

[1704 rows x 3 columns]

In [ ]:
df.[["life_exp", "country", "year"]]

SyntaxError: invalid syntax (<ipython-input-97-e92ab696560e>, line 1)

In [ ]:
df.loc[:,["life_exp", "country", "year"]]

      life_exp      country  year
10      28.801  Afghanistan  1952
11      30.332  Afghanistan  1957
12      31.997  Afghanistan  1962
13      34.020  Afghanistan  1967
14      36.088  Afghanistan  1972
...        ...          ...   ...
1709    62.351     Zimbabwe  1987
1710    60.377     Zimbabwe  1992
1711    46.809     Zimbabwe  1997
1712    39.989     Zimbabwe  2002
1713    43.487     Zimbabwe  2007

[1704 rows x 3 columns]

In [ ]:
df.iloc[:,0:2]

          country  year
10    Afghanistan  1952
11    Afghanistan  1957
12    Afghanistan  1962
13    Afghanistan  1967
14    Afghanistan  1972
...           ...   ...
1709     Zimbabwe  1987
1710     Zimbabwe  1992
1711     Zimbabwe  1997
1712     Zimbabwe  2002
1713     Zimbabwe  2007

[1704 rows x 2 columns]

In [ ]:
a = df.iloc[:2,:2]                           #line a
b = df.loc[:2,"country":"population"]           #line b

print(a)


print(b)

        country  year
10  Afghanistan  1952
11  Afghanistan  1957
Empty DataFrame
Columns: [country, year, population]
Index: []